name: Test Docker

on:
    push:
        branches: master

jobs:
    docker-container:
        name: Docker
        runs-on: ubuntu-latest
        steps:
          - name: Checkout Repo
            uses: actions/checkout@v4

          - name: Pull Latest Docker image
            run: |
                latest_tag=$(git tag --sort=-v:refname | grep -E '^v[0-9]+\.[0-9]+\.[0-9]+$' | head -n 1)
                docker pull ghcr.io/nicconike/automatedgo:$latest_tag

          - name: Test Docker Container (Abort Download)
            run: |
                echo "no" | docker run --rm --name automatedgo-abort \
                    ghcr.io/nicconike/automatedgo:master \
                    --os linux \
                    --arch amd64

          - name: Test Docker Container (Confirm Download)
            run: |
                echo "yes" | docker run --rm --name automatedgo-confirm \
                    -v ${{ github.workspace }}:/automatedgo \
                    ghcr.io/nicconike/automatedgo:master \
                    --os linux \
                    --arch amd64
