name: Test Docker

on:
    push:
        branches: master

jobs:
    docker-container:
        runs-on: ubuntu-latest
        steps:
          - name: Checkout Repo
            uses: actions/checkout@v4

        #   - name: Login to Docker Hub
        #     uses: docker/login-action@v3
        #     with:
        #         username: ${{ vars.DOCKER_USERNAME }}
        #         password: ${{ secrets.DOCKER_TOKEN }}

          - name: Login to GitHub Container Registry
            uses: docker/login-action@v3
            with:
                registry: ghcr.io
                username: ${{ github.actor }}
                password: ${{ secrets.GITHUB_TOKEN }}

          - name: Pull Docker image
            run: docker pull nicconike/automatedgo:master

          - name: Test Docker Container for Dockerfile
            run: |
                docker run --rm --name automatedgo-dockerfile \
                    -v ${{ github.workspace }}/files:/automatedgo/files \
                    nicconike/automatedgo:master \
                    --file /automatedgo/files/Dockerfile \
                    --os linux \
                    --arch amd64

          - name: Test Docker Container for JSON
            run: |
                docker run --rm --name automatedgo-json \
                    -v ${{ github.workspace }}/files:/automatedgo/files \
                    nicconike/automatedgo:master \
                    --file /automatedgo/files/go.json \
                    --os linux \
                    --arch amd64

          - name: Test Docker Container for Text files
            run: |
                docker run --rm --name automatedgo-txt \
                    -v ${{ github.workspace }}/files:/automatedgo/files \
                    nicconike/automatedgo:master \
                    --file /automatedgo/files/version.txt \
                    --os linux \
                    --arch amd64

        #   - name: Clean up
        #     if: always()
        #     run: |
        #         docker stop automatedgo-container
        #         docker rm automatedgo-container
