name: Test Docker

on:
    push:
        branches: master

jobs:
    docker-container:
        runs-on: ubuntu-latest
        steps:
          - name: Checkout Repo
            uses: actions/checkout@v4

          - name: Login to Docker Hub
            uses: docker/login-action@v3
            with:
                username: ${{ vars.DOCKER_USERNAME }}
                password: ${{ secrets.DOCKER_TOKEN }}

          - name: Pull Docker image
            run: docker pull nicconike/automatedgo:master

          - name: Run Docker Container
            run: |
                docker run --name automatedgo-container nicconike/automatedgo:master \
                    --file files/Dockerfile \
                    --os linux \
                    --arch amd64

          - name: Clean up
            if: always()
            run: |
                docker stop automatedgo-container
                docker rm automatedgo-container
